version: '3.9'

services:
  db-cpa:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - services-network-cpa

  backend-cpa:
    image: cpa/backend
    build: ./cpa_back
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db-cpa:3308/${MYSQL_DATABASE}
      SPRING.DATASOURCE.USERNAME: ${MYSQL_USER}
      SPRING.DATASOURCE.PASSWORD: ${MYSQL_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      CORS.ORIGINFRONT: ${CORS_FRONT}
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      db-cpa:
        restart: true
        condition: service_healthy
    networks:
      - services-network-cpa

networks:
  services-network-cpa:
      driver: bridge    